name:                extensible-frames
version:             0.1.0.0
github:              "fumieval/extensible-frames"
license:             BSD3
author:              "Fumiaki Kinoshita"
maintainer:          "fumiexcel@gmail.com"
copyright:           "2018 Fumiaki Kinoshita"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/fumieval/extensible-frames#readme>

dependencies:
- base >= 4.7 && < 5
- cassava
- extensible
- vector
- bytestring
- primitive
- text
- text-short

library:
  source-dirs: src
  ghc-options: -Wall
  default-extensions:
    - DataKinds
    - PolyKinds
    - FlexibleContexts
    - ScopedTypeVariables
    - TypeOperators
